version: 2

sources:
  - name: public
    description: "Tables brutes dans PostgreSQL"
    tables:
      - name: staging_reviews
        description: "Avis collectés depuis Google Maps"
        columns:
          - name: bank
            description: "Nom de la banque"
          - name: agency
            description: "Nom de l'agence"
          - name: rating
            description: "Note de 1 à 5"
          - name: review_text
            description: "Texte de l'avis"
      
      - name: sentiment_analysis
        description: "Résultats de l'analyse de sentiment"
        columns:
          - name: review_id
            description: "ID unique de l'avis"
          - name: sentiment
            description: "Sentiment: positive, negative, neutral"
          - name: vader_compound
            description: "Score VADER (-1 à 1)"
          - name: textblob_polarity
            description: "Polarité TextBlob"
          - name: confidence
            description: "Niveau de confiance"
      
      # NOUVELLE TABLE POUR LES TOPICS
      - name: topic_analysis
        description: "Résultats de l'extraction de topics LDA"
        columns:
          - name: review_id
            description: "ID unique de l'avis"
          - name: dominant_topic
            description: "Topic dominant (0-4)"
          - name: topic_category
            description: "Catégorie du topic"
          - name: topic_keywords
            description: "Mots-clés du topic"
          - name: topic_confidence
            description: "Confiance du topic"
          - name: language
            description: "Langue détectée"